name: response_parser
description: Response Parser makes it easier to parse data and error response from server
version: 1.0.0+1
repository: https://github.com/qyre-ab/response_parser

environment:
  sdk: ">=2.17.3 <3.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

dependencies:
  fpdart: ">=0.2.0 <0.5.0"
